### ISSUE TITLE
Fails when used to deploy new Data Factories

### ISSUE THREAD

**Issue by zehndean** [Azure/data-factory-deploy-action#1]
When the action is used to deploy a Data Factory with a name that does not already exist, the Actions fails with the following message:

```
Run /home/runner/work/_actions/Azure/data-factory-deploy-action/v1.1.0/PrePostDeploymentScript.ps1 `
Getting triggers
Get-AzDataFactoryV2Trigger: /home/runner/work/_actions/Azure/data-factory-deploy-action/v1.1.0/PrePostDeploymentScript.ps1:92
Line |
  92 |  … $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGr …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | HTTP Status Code: NotFound Error Code: ResourceNotFound
     | Error Message: The Resource
     | 'Microsoft.DataFactory/factories/test-datafactory'
     | under resource group 'test' was not found. For more
     | details please go to https://aka.ms/ARMResourceNotFoundFix
     | Request Id: 1afdfeca-77af-4a3e-a7d1-2071579445 Timestamp
     | (Utc):09/29/2021 13:54:29

Error: Process completed with exit code 1.
```

When the Datafactory has already been created (e.g. through Azure Portal), the same action works.

Please enhance the action in a way that it works with initial deployments of DataFactory as well.

**Comment by fedeoliv** [comment]
@zehndean thanks for opening the issue! This GitHub Action isn't designed to deploy a Data Factory instance, but deploying resources (e.g. dataflows, datasets, pipelines, triggers, linked services, integration runtime) inside an existing Data Factory.

**Comment by fedeoliv** [comment]
I've updated the GitHub Action description and prerequisites, let me know if it's better now. Thanks!

**Comment by zehndean** [comment]
Ah, thanks for the information! I still think that it would be an interesting enhancement of the action to work both ways but it is now clear that that was not the original goal. Thus the issue can be closed.
