### ISSUE TITLE
Can not install AZ every time execute

### ISSUE THREAD

**Issue by mayong43111** [Azure/data-factory-deploy-action#6]
Dear,
I used this action on a corporate project, I have a problem that it takes too long to install AZ each time. Even though I had installed AZ before, this step was too long . Thank you very much and hope you can remove it . I know this can be difficult for people who don't use self-host, But whether you can add a check or use an argument as an option ?

**Comment by fedeoliv** [comment]
Hey @mayong43111 thanks for your feedback! I see, adding an option to skip the Az module installation makes sense for self-hosted scenarios. What if we add a `skipAzModuleInstallation` optional argument?

**Comment by mayong43111** [comment]
@fedeoliv That's a great idea.

**Comment by mayong43111** [comment]
Hi @fedeoliv , I started a pull request. #7

**Comment by fedeoliv** [comment]
Great, thanks for your contribution! I'll close this out and release a new version `1.2.0`.

**Comment by mayong43111** [comment]
thank you, fedeoliv,
